/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system_gym;

import javax.swing.JOptionPane;

/**
 *
 * @author deyby-dev
 */
public class CreateExerciseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateExerciseForm.class.getName());
    
    // Variables to remember selected value.
    private String selectedType = "";
    private String selectedLevel = "";

    /**
     * Creates new form CreateExerciseForm
     */
    public CreateExerciseForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StrengthType = new javax.swing.JButton();
        CardioType = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BeginnerLevel = new javax.swing.JButton();
        IntermediateLevel = new javax.swing.JButton();
        AdvancedLevel = new javax.swing.JButton();
        HighLevel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        EstimatedField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Create Exercise");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Type of Exercise: ");

        StrengthType.setText("Strength");
        StrengthType.addActionListener(this::StrengthTypeActionPerformed);

        CardioType.setText("Cardio");
        CardioType.addActionListener(this::CardioTypeActionPerformed);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Level of Exercise:");

        BeginnerLevel.setText("Beginner");
        BeginnerLevel.addActionListener(this::BeginnerLevelActionPerformed);

        IntermediateLevel.setText("Intermediate");
        IntermediateLevel.addActionListener(this::IntermediateLevelActionPerformed);

        AdvancedLevel.setText("Advanced");
        AdvancedLevel.addActionListener(this::AdvancedLevelActionPerformed);

        HighLevel.setText("High Performance");
        HighLevel.addActionListener(this::HighLevelActionPerformed);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Estimated Time:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("Description: ");

        SaveButton.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(this::SaveButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StrengthType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(CardioType, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BeginnerLevel)
                                .addGap(31, 31, 31)
                                .addComponent(IntermediateLevel)
                                .addGap(18, 18, 18)
                                .addComponent(AdvancedLevel)
                                .addGap(18, 18, 18)
                                .addComponent(HighLevel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(44, 44, 44)
                                .addComponent(DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NameField)
                                    .addComponent(EstimatedField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StrengthType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardioType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeginnerLevel)
                    .addComponent(IntermediateLevel)
                    .addComponent(AdvancedLevel)
                    .addComponent(HighLevel))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EstimatedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StrengthTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrengthTypeActionPerformed
        selectedType = "Strength";
    }//GEN-LAST:event_StrengthTypeActionPerformed

    private void CardioTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardioTypeActionPerformed
        selectedType = "Cardio";
    }//GEN-LAST:event_CardioTypeActionPerformed

    private void BeginnerLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginnerLevelActionPerformed
        selectedLevel = "Beginner";
    }//GEN-LAST:event_BeginnerLevelActionPerformed

    private void IntermediateLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntermediateLevelActionPerformed
        selectedLevel = "Intermediate";
    }//GEN-LAST:event_IntermediateLevelActionPerformed

    private void AdvancedLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedLevelActionPerformed
        selectedLevel = "Advanced";
    }//GEN-LAST:event_AdvancedLevelActionPerformed

    private void HighLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighLevelActionPerformed
        selectedLevel = "High Performance";
    }//GEN-LAST:event_HighLevelActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (selectedType.isEmpty() || selectedLevel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a type and a level.");
            return;
        }

        String name = NameField.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name is required.");
            return;
        }

        double estimatedTime;
        try {
            estimatedTime = Double.parseDouble(EstimatedField.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Estimated time must be a number.");
            return;
        }

        String description = DescriptionField.getText().trim();

        Exercise exercise;
        if (selectedType.equals("Strength")) {
            exercise = new Strength(name, selectedLevel, estimatedTime, description, 0);
        } else {
            exercise = new Cardio(name, selectedLevel, estimatedTime, description, 0);
        }

        ExerciseDAO dao = new ExerciseDAO();
        boolean success = dao.createExercise(exercise);

        if (success) {
            JOptionPane.showMessageDialog(null, "Exercise created successfully!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error: could not save the exercise.");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateExerciseForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdvancedLevel;
    private javax.swing.JButton BeginnerLevel;
    private javax.swing.JButton CardioType;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTextField EstimatedField;
    private javax.swing.JButton HighLevel;
    private javax.swing.JButton IntermediateLevel;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton StrengthType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
