/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system_gym;

import javax.swing.JOptionPane;

/**
 *
 * @author deyby-dev
 */
public class CreateExerciseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateExerciseForm.class.getName());
    
    private Exercise exerciseToEdit = null;

    /**
     * Opens the form in CREATE mode.
     */
    public CreateExerciseForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Opens the form in UPDATE mode with fields pre-filled from the given exercise.
     *
     * @param e The exercise to edit.
     */
    public CreateExerciseForm(Exercise e) {
        initComponents();
        setLocationRelativeTo(null);

        exerciseToEdit = e;

        jLabel1.setText("Update Exercise");
        SaveButton.setText("Update");
        NameField.setText(e.getName());
        EstimatedField.setText(String.valueOf(e.getEstimatedTime()));
        DescriptionField.setText(e.getDescription());

        if (e.getType().equals("Strength")) StrengthOption.setSelected(true);
        else CardioOption.setSelected(true);

        switch (e.getIntensityLevel()) {
            case "Beginner"        -> BeginnerOption.setSelected(true);
            case "Intermediate"    -> IntermediateOption.setSelected(true);
            case "Advanced"        -> AdvancedOption.setSelected(true);
            case "High Performance"-> HighOption.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypeGroup = new javax.swing.ButtonGroup();
        LevelGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        EstimatedField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        StrengthOption = new javax.swing.JRadioButton();
        CardioOption = new javax.swing.JRadioButton();
        IntermediateOption = new javax.swing.JRadioButton();
        BeginnerOption = new javax.swing.JRadioButton();
        AdvancedOption = new javax.swing.JRadioButton();
        HighOption = new javax.swing.JRadioButton();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Create Exercise");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Type of Exercise: ");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Level of Exercise:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Estimated Time:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("Description: ");

        SaveButton.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(this::SaveButtonActionPerformed);

        TypeGroup.add(StrengthOption);
        StrengthOption.setText("Strength");

        TypeGroup.add(CardioOption);
        CardioOption.setText("Cardio");

        LevelGroup.add(IntermediateOption);
        IntermediateOption.setText("Intermediate");

        LevelGroup.add(BeginnerOption);
        BeginnerOption.setText("Beginner");

        LevelGroup.add(AdvancedOption);
        AdvancedOption.setText("Advanced");

        LevelGroup.add(HighOption);
        HighOption.setText("High Performance");

        Close.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        Close.setText("Close");
        Close.addActionListener(this::CloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstimatedField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(658, 658, 658))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StrengthOption)
                                .addGap(66, 66, 66)
                                .addComponent(CardioOption))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BeginnerOption)
                                .addGap(35, 35, 35)
                                .addComponent(IntermediateOption)
                                .addGap(34, 34, 34)
                                .addComponent(AdvancedOption)
                                .addGap(41, 41, 41)
                                .addComponent(HighOption)))
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(419, 572, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StrengthOption)
                    .addComponent(CardioOption))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BeginnerOption)
                            .addComponent(IntermediateOption)
                            .addComponent(AdvancedOption)
                            .addComponent(HighOption))
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EstimatedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(194, 194, 194))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        boolean noTypeSelected  = !StrengthOption.isSelected() && !CardioOption.isSelected();
        boolean noLevelSelected = !BeginnerOption.isSelected() && !IntermediateOption.isSelected()
                               && !AdvancedOption.isSelected() && !HighOption.isSelected();

        if (noTypeSelected || noLevelSelected) {
            JOptionPane.showMessageDialog(null, "Please select a type and a level.");
            return;
        }

        String name = NameField.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name is required.");
            return;
        }

        double estimatedTime;
        try {
            estimatedTime = Double.parseDouble(EstimatedField.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Estimated time must be a number.");
            return;
        }

        String description = DescriptionField.getText().trim();

        String selectedType  = StrengthOption.isSelected() ? "Strength" : "Cardio";
        String selectedLevel;
        if      (BeginnerOption.isSelected())     selectedLevel = "Beginner";
        else if (IntermediateOption.isSelected())  selectedLevel = "Intermediate";
        else if (AdvancedOption.isSelected())      selectedLevel = "Advanced";
        else                                       selectedLevel = "High Performance";

        Exercise exercise;
        if (selectedType.equals("Strength")) {
            exercise = new Strength(name, selectedLevel, estimatedTime, description, 0);
        } else {
            exercise = new Cardio(name, selectedLevel, estimatedTime, description, 0);
        }

        ExerciseDAO dao = new ExerciseDAO();
        boolean success;

        if (exerciseToEdit == null) {
            success = dao.createExercise(exercise);
        } else {
            exercise.setId(exerciseToEdit.getId());
            success = dao.updateExercise(exercise);
        }

        if (success) {
            String msg = (exerciseToEdit == null) ? "Exercise created successfully!" : "Exercise updated successfully!";
            JOptionPane.showMessageDialog(null, msg);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error: could not save the exercise.");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateExerciseForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdvancedOption;
    private javax.swing.JRadioButton BeginnerOption;
    private javax.swing.JRadioButton CardioOption;
    private javax.swing.JButton Close;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTextField EstimatedField;
    private javax.swing.JRadioButton HighOption;
    private javax.swing.JRadioButton IntermediateOption;
    private javax.swing.ButtonGroup LevelGroup;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JRadioButton StrengthOption;
    private javax.swing.ButtonGroup TypeGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
