package system_gym;

import javax.swing.JOptionPane;

/**
 * Form that displays the full detail of a single exercise in read-only mode.
 * The user selects an exercise by ID and this window shows all its fields.
 */
public class ShowExerciseDetailForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ShowExerciseDetailForm.class.getName());

    /**
     * Opens the form and pre-fills all fields with the given exercise data.
     *
     * @param e The exercise whose details will be displayed.
     */
    public ShowExerciseDetailForm(Exercise e) {
        initComponents();
        setLocationRelativeTo(null);

        // Fill every read-only field with the exercise data
        NameValue.setText(e.getName());
        TypeValue.setText(e.getType());
        LevelValue.setText(e.getIntensityLevel());
        TimeValue.setText(e.getEstimatedTime() + " min");
        DescriptionValue.setText(e.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();

        NameLabel = new javax.swing.JLabel();
        NameValue = new javax.swing.JTextField();

        TypeLabel = new javax.swing.JLabel();
        TypeValue = new javax.swing.JTextField();

        LevelLabel = new javax.swing.JLabel();
        LevelValue = new javax.swing.JTextField();

        TimeLabel = new javax.swing.JLabel();
        TimeValue = new javax.swing.JTextField();

        DescriptionLabel = new javax.swing.JLabel();
        DescriptionValue = new javax.swing.JTextField();

        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercise Detail");

        TitleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        TitleLabel.setText("Exercise Detail");

        NameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NameLabel.setText("Name:");
        NameValue.setFont(new java.awt.Font("Liberation Sans", 0, 16));
        NameValue.setEditable(false);

        TypeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        TypeLabel.setText("Type:");
        TypeValue.setFont(new java.awt.Font("Liberation Sans", 0, 16));
        TypeValue.setEditable(false);

        LevelLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LevelLabel.setText("Intensity Level:");
        LevelValue.setFont(new java.awt.Font("Liberation Sans", 0, 16));
        LevelValue.setEditable(false);

        TimeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        TimeLabel.setText("Estimated Time:");
        TimeValue.setFont(new java.awt.Font("Liberation Sans", 0, 16));
        TimeValue.setEditable(false);

        DescriptionLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        DescriptionLabel.setText("Description:");
        DescriptionValue.setFont(new java.awt.Font("Liberation Sans", 0, 16));
        DescriptionValue.setEditable(false);

        CloseButton.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(this::CloseButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLabel,        javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeLabel,        javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelLabel,       javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeLabel,        javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameValue,        javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeValue,        javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelValue,       javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeValue,        javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(TypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LevelLabel)
                    .addComponent(LevelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLabel)
                    .addComponent(TimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionLabel)
                    .addComponent(DescriptionValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            // Demo mode: show a dummy exercise for testing
            Exercise demo = new Exercise(1, "Demo Exercise", "Cardio", "Beginner", 30.0, "Sample description", 0);
            new ShowExerciseDetailForm(demo).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel  TitleLabel;
    private javax.swing.JLabel  NameLabel;
    private javax.swing.JTextField NameValue;
    private javax.swing.JLabel  TypeLabel;
    private javax.swing.JTextField TypeValue;
    private javax.swing.JLabel  LevelLabel;
    private javax.swing.JTextField LevelValue;
    private javax.swing.JLabel  TimeLabel;
    private javax.swing.JTextField TimeValue;
    private javax.swing.JLabel  DescriptionLabel;
    private javax.swing.JTextField DescriptionValue;
    private javax.swing.JButton CloseButton;
    // End of variables declaration//GEN-END:variables
}
